In [1]:
import scipy.stats as stats
import seaborn as sns
import pandas as pd
import numpy as np

Matplotlib is building the font cache; this may take a moment.


In [20]:
file=pd.read_csv('C:/Users/AbdulAzeez/Downloads/file.csv')

In [22]:
file

Gender           Age      Religion   Tribe  Level Statistics  \
0      Male         25-29        Others    Igbo  HND 2         No   
1    Female         20-24         Islam  Yoruba  HND 2        Yes   
2      Male         25-29         Islam  Yoruba  HND 2        Yes   
3      Male         25-29         Islam  Yoruba  HND 2         No   
4    Female         25-29         Islam  Yoruba  HND 2        Yes   
..      ...           ...           ...     ...    ...        ...   
278  Female         20-24  Christianity    Igbo   ND 1        Yes   
279    Male         20-24  Christianity  Yoruba   ND 1        Yes   
280  Female         20-24  Christianity  Yoruba   ND 1         No   
281  Female  Less than 20         Islam  Yoruba   ND 1        Yes   
282    Male         20-24  Christianity  Yoruba   ND 1         No   

            Grade             Option           Option.1        Option.2  ...  \
0    Upper Credit              Agree     Strongly Agree           Agree  ...   
1    Lower Credit              Agree           Disagree           Agree  ...   
2            Pass  Strongly Disagree              Agree           Agree  ...   
3            Pass  Strongly Disagree  Strongly Disagree  Strongly Agree  ...   
4            Pass              Agree              Agree        Disagree  ...   
..            ...                ...                ...             ...  ...   
278     Probation              Agree              Agree           Agree  ...   
279  Lower Credit              Agree     Strongly Agree           Agree  ...   
280          Pass              Agree           Disagree           Agree  ...   
281  Upper Credit              Agree           Disagree           Agree  ...   
282           NaN              Agree           Disagree           Agree  ...   

              Option.7  Option.8           Option.9       Option.10  \
0             Disagree     Agree              Agree           Agree   
1             Disagree     Agree              Agree  Strongly Agree   
2             Disagree  Disagree  Strongly Disagree           Agree   
3    Strongly Disagree     Agree              Agree           Agree   
4                Agree  Disagree              Agree           Agree   
..                 ...       ...                ...             ...   
278              Agree     Agree              Agree        Disagree   
279           Disagree  Disagree              Agree        Disagree   
280              Agree     Agree              Agree  Strongly Agree   
281              Agree     Agree              Agree           Agree   
282              Agree     Agree              Agree  Strongly Agree   

          Option.11       Option.12       Option.13       Option.14  \
0    Strongly Agree           Agree  Strongly Agree        Disagree   
1          Disagree           Agree           Agree           Agree   
2          Disagree           Agree        Disagree        Disagree   
3             Agree  Strongly Agree  Strongly Agree        Disagree   
4          Disagree           Agree           Agree        Disagree   
..              ...             ...             ...             ...   
278        Disagree           Agree           Agree  Strongly Agree   
279           Agree  Strongly Agree           Agree        Disagree   
280  Strongly Agree  Strongly Agree  Strongly Agree           Agree   
281        Disagree           Agree           Agree           Agree   
282  Strongly Agree  Strongly Agree  Strongly Agree  Strongly Agree   

          Option.15       Option.16  
0          Disagree  Strongly Agree  
1             Agree        Disagree  
2             Agree           Agree  
3          Disagree        Disagree  
4             Agree        Disagree  
..              ...             ...  
278        Disagree           Agree  
279           Agree        Disagree  
280           Agree  Strongly Agree  
281        Disagree           Agree  
282  Strongly Agree  Strongly Agree  

[283 rows x 24 columns]

In [23]:
file_table=pd.crosstab(file['Gender'], file['Grade'])
print(file_table)

Grade   Distinction  Lower Credit  Pass  Probation  Upper Credit  Withdrawal
Gender                                                                      
Female           12            52    28          4            40           1
Male             14            38    34         10            37           2


In [45]:
file.isnull().sum()
file.dropna(inplace=True)

In [54]:
file.isnull()

Gender    Age  Religion  Tribe  Level  Statistics  Grade  Option  \
0     False  False     False  False  False       False  False   False   
1     False  False     False  False  False       False  False   False   
2     False  False     False  False  False       False  False   False   
3     False  False     False  False  False       False  False   False   
4     False  False     False  False  False       False  False   False   
..      ...    ...       ...    ...    ...         ...    ...     ...   
277   False  False     False  False  False       False  False   False   
278   False  False     False  False  False       False  False   False   
279   False  False     False  False  False       False  False   False   
280   False  False     False  False  False       False  False   False   
281   False  False     False  False  False       False  False   False   

     Option.1  Option.2  ...  Option.7  Option.8  Option.9  Option.10  \
0       False     False  ...     False     False     False      False   
1       False     False  ...     False     False     False      False   
2       False     False  ...     False     False     False      False   
3       False     False  ...     False     False     False      False   
4       False     False  ...     False     False     False      False   
..        ...       ...  ...       ...       ...       ...        ...   
277     False     False  ...     False     False     False      False   
278     False     False  ...     False     False     False      False   
279     False     False  ...     False     False     False      False   
280     False     False  ...     False     False     False      False   
281     False     False  ...     False     False     False      False   

     Option.11  Option.12  Option.13  Option.14  Option.15  Option.16  
0        False      False      False      False      False      False  
1        False      False      False      False      False      False  
2        False      False      False      False      False      False  
3        False      False      False      False      False      False  
4        False      False      False      False      False      False  
..         ...        ...        ...        ...        ...        ...  
277      False      False      False      False      False      False  
278      False      False      False      False      False      False  
279      False      False      False      False      False      False  
280      False      False      False      False      False      False  
281      False      False      False      False      False      False  

[272 rows x 24 columns]

In [55]:
file.isnull().sum()

Gender        0
Age           0
Religion      0
Tribe         0
Level         0
Statistics    0
Grade         0
Option        0
Option.1      0
Option.2      0
Option.3      0
Option.4      0
Option.5      0
Option.6      0
Option.7      0
Option.8      0
Option.9      0
Option.10     0
Option.11     0
Option.12     0
Option.13     0
Option.14     0
Option.15     0
Option.16     0
dtype: int64

In [46]:
file_table.values

array([[12, 52, 28,  4, 40,  1],
       [14, 38, 34, 10, 37,  2]], dtype=int64)

In [47]:
observe_values = file_table.values
print('observe_values :-\n', observe_values)

observe_values :-
 [[12 52 28  4 40  1]
 [14 38 34 10 37  2]]


In [48]:
val=stats.chi2_contingency(file_table)

In [49]:
val

(5.919528275906375,
 0.3141281021211128,
 5,
 array([[13.09558824, 45.33088235, 31.22794118,  7.05147059, 38.78308824,
          1.51102941],
        [12.90441176, 44.66911765, 30.77205882,  6.94852941, 38.21691176,
          1.48897059]]))

In [50]:
Expected_Values= val[3]

In [33]:
no_of_rows=len(file_table.iloc[0:2,0])
no_of_columns=len(file_table.iloc[0,0:6])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of freedom: ", ddof)
alpha= 0.05

Degree of freedom:  5


In [51]:
from scipy.stats import chi2

In [52]:
chi_square= sum([(o-e)**2./e for o,e in zip(observe_values,Expected_Values)])
chi_square_statistic= chi_square[0]+chi_square[1]

In [56]:
print('chi-sqr stat: ',chi_square_statistic )

chi-sqr stat:  2.161541835053596


In [58]:
critical_value=chi2.ppf(q=1-alpha, df=ddof)
print('critical value: ', critical_value)

critical value:  11.070497693516351


In [69]:
p_value=1-chi2.cdf('X'==chi_square_statistic, df=ddof)
print('p-value: ', p_value)
print('significance leve: ', alpha)
print('degree of freedom: ', ddof)

p-value:  1.0
significance leve:  0.05
degree of freedom:  5
